### PR TITLE
fix(package): add `webpack >= v4.0.0` (`peerDependencies`)

### PR DESCRIPTION
**Pull request by ai**
Oops, I forgot about `peerDependencies`. Is it correct?

### CODE REVIEW

**Comment by ai** [comment]
@michael-ciniawsky or should I use `^4.0.0-beta.2`?

**Comment by michael-ciniawsky** [comment]
The webpack 4 release should be around the 24th, better to leave this clean and wait 1-2 days in this case :)

**Comment by ai** [comment]
@michael-ciniawsky fixed

**Comment by michael-ciniawsky** [comment]
I will release them with the `webpack` 4 release, which hopefully is within the next 1-2 days as announced. Otherwise I fix/add `beta` versions as well in meantime I kept a note :)

**Pull request merged**
