### PR TITLE
>=, not =<

### PR DESCRIPTION
**Pull request by xhlwill**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@xhlwill Only webpack@3 and lower contain 0.4.6 version

**Comment by xhlwill** [comment]
Isn't webpack>=3.0.0 <4 contain 0.4.6

**Comment by evilebottnawi** [comment]
@xhlwill agree some misleading, let's rewrite to `webpack < v4.0.0`

**Comment by evilebottnawi** [comment]
@xhlwill also please accept CLA

**Comment by d3viant0ne** [comment]
Please rebase with current master

**Comment by xhlwill** [comment]
Is it right...

**Comment by evilebottnawi** [comment]
@xhlwill can you rebase again?

**Pull request merged**
