### PR TITLE
fix(uglify/worker): better `{Error}` handling

### PR DESCRIPTION
**Pull request by evilebottnawi**

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
Could you please show a screenshot of the output ? Nice if it already works with this elegant change :)

**Comment by michael-ciniawsky** [comment]
Also the `{Error}` shape/type of the `err` before pushing to `compilation.errors` needs to be checked :)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky what do you mean? :smile:

**Comment by michael-ciniawsky** [comment]
A screenshot/logs of the {Error} and what does the worker return as `err` `{String|Object}` `{Object} === instanceof Error` (when it is passed to `compilation.errors.push(err)`) ? 🙃

**Comment by michael-ciniawsky** [comment]
Could we clearify if this definitely fixes the `{Error}` handling and get this PR and #243 out asap ? :)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky :+1:

**Comment by evilebottnawi** [comment]
@michael-ciniawsky also remove error handle, because we already push error

**Comment by evilebottnawi** [comment]
@michael-ciniawsky thos solution don't works because we can't build `UglifyJsPlugin.buildError` we should serialize error for right account :disappointed:

**Comment by michael-ciniawsky** [comment]
Can you explain this a bit more detailed please :) ? The `buildUglifyError` could maybe made it's own`{Error}` Class instead, which handles the serialized error `{String|Object}`

**Uglify[Worker]Error.js**
```js
class Uglify[Worker]Error extends Error {
   constructor (serialized) {
      const err = JSON.parse(serialized)
       
      this.name = err.name
      this.message = `\n\n(${err.line}:${err.column} ${err.message}...\n`
      
      Error.captureStackTrace(this, this.constructor)
   }
}

module.exports = Uglify[Worker]Error
```

**Comment by d3viant0ne** [comment]
Please rebase with current master

**Comment by evilebottnawi** [comment]
@michael-ciniawsky apparently something was wrongly installed or configured, the problem is no longer there

**Pull request closed without merging**
