### PR TITLE
chore(package): move `uglifyjs` back to `peerDependencies`

### LINKED ISSUE #49: can not support es6 minification after upgrade to 0.4.6
the `0.4.6` version move the `uglify2` to `dependencies`, so I can't specify the `uglify2` version through `yarn add git://github.com/mishoo/UglifyJS2#harmony-v2.8.22 --dev`. cause the plugin will use its own dependency - `uglify-js^2.8.29`.

### PR DESCRIPTION
**Pull request by sandfox**
this partially reverts 6e8948ee3a0a0a12f049c829b82d409d102648a3 and puts uglify as a peer dep again so that consumers can continue to use the es branch of uglify.

(And this means the module now also matches up again with the README / docs)

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@sandfox it is break `webpack`

**Comment by evilebottnawi** [comment]
@sandfox we known about this problems and try to found solution asap

**Comment by michael-ciniawsky** [comment]
Fixes #49

**Comment by sokra** [comment]
A solution could be to merge this and add uglifyjs to webpack des.

**Comment by evilebottnawi** [comment]
@sokra before merge we need to add `uglify-js` to `webpack` and release patch version, or we break `webpack` again, also after merge, `webpack` version 3.0.0 was break.

**Comment by sokra** [comment]
yep, send a PR.

**Comment by evilebottnawi** [comment]
**After release `webpack` v3.0.1 we can merge this and release new version** (if we merge now and release we can break webpack v3.0.0)

**Comment by michael-ciniawsky** [comment]
Superseded by #63 thx :)

**Pull request closed without merging**
