### PR TITLE
test: added tests to ensure correct uglify-es version is being used.

### PR DESCRIPTION
**Pull request by hulkish**
Fixes https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/67#issuecomment-313425627

### CODE REVIEW

**Comment by d3viant0ne** [comment]
screen shot 2017-07-07 at 11 40 22 am

Attack of the modules .... again ! :p

**Comment by hulkish** [comment]
Jeez, i guess i was incorrectly assuming the uglify-es version as the cause. what does this print out for u?

```bash
node -v
npm -v
cat node_modules/webpack/package.json | grep version
cat node_modules/uglify-es/package.json | grep version
cat node_modules/uglify-js/package.json | grep version
```

**Comment by d3viant0ne** [comment]
screen shot 2017-07-07 at 12 05 17 pm

**Comment by hulkish** [comment]
@d3viant0ne can u try installing npm >= 5? I suspect it's related to package-lock.json not being respected.

**Comment by michael-ciniawsky** [comment]
It sometimes works locally (macOS) for me, but the test are definitely flaky. But what is this test actually testing here ? 🙃

**Comment by hulkish** [comment]
@michael-ciniawsky the test in this PR is not actually intended to be merged. Just an attempt to find the cause of this issue.

**Pull request closed without merging**
