### PR TITLE
fixes #70

### LINKED ISSUE #70: all folders missing from package on npm install
Version: master

Hi,

since you added ./dist/ to gitignore its not anymore included when installed via npm. The other folders aren't included either since you specified files: ["dist"] in package.json.

Greetings, Sascha

### PR DESCRIPTION
**Pull request by torvitas**
Adds postinstall script, moves build tools from devDependencies to dependencies to build on install, adds src to files because npm removes most stuff that isnt listed there.

This fixes #70

### CODE REVIEW

**Comment by torvitas** [comment]
Could someone please review the appveyor tests?

**Comment by evilebottnawi** [comment]
@torvitas we use `webpack-defaults` base repo for all `webpack-contrib` repos, PR is invalid, why your need `src` directory?

**Comment by torvitas** [comment]
As described in the linked issue, because you added ./dist to gitignore npm doesn't include it when installed via npm install. I solved that by adding a postinstall script that compiles dist on installation.

Where do you want me to PR?

**Comment by evilebottnawi** [comment]
@torvitas npm don't use `.gitignore` for ignoring files, npm use `.npmignore`

**Comment by torvitas** [comment]
You do not have ./dist in the repository at all.

**Comment by evilebottnawi** [comment]
@torvitas why we need `dist` in repo? Code in `dist` generate automatically before publish in npm

**Comment by torvitas** [comment]
You didn't publish yet. The way the package is right now it is not possible to install.

Try to npm install git+https://github.com/webpack-contrib/uglifyjs-webpack-plugin.git#master there will be an almost empty folder in node_modules/uglify-webpack-plugin

**Comment by evilebottnawi** [comment]
@torvitas don't need PR, just wait when some bug will be fixed and release will be publish

**Comment by torvitas** [comment]
Well .. there is no sense in having an not installable beta. But I also got there is no willingness to accept my PR at all. You didn't even try to understand the problem I am trying to solve here.

Over and out.

**Comment by evilebottnawi** [comment]
@torvitas i understand your problems, there is not publish release because current master can contain bug (or unexpected behavior).

**Comment by torvitas** [comment]
#issuecomment-313692335 completely solved it

**Pull request closed without merging**
