### PR TITLE
update plugin

### LINKED ISSUE #8: Update plugin
[Several commits](https://github.com/webpack/webpack/commits/master/lib/optimize/UglifyJsPlugin.js) have been applied to the plugin in webpack/webpack, so we should update it here as well.

Simply copying the new version will lead to a bunch of linting errors, because the projects use different eslint configurations.

### PR DESCRIPTION
**Pull request by SebastianS90**
I just copied the webpack/webpack lib/optimize/UglifyJsPlugin.js and fixed the [relative requires](https://github.com/webpack/webpack/blob/d0f1f6e77009599618b571f9d57bb2a53ba1a583/lib/optimize/UglifyJsPlugin.js#L11:L12).

TODO:
- [x] Update Changelog (look through commits in webpack/webpack)
- ~~Update eslint configuration to be the same as in webpack/webpack~~
- ~~Update remaining js files to be conform with the new eslint configuration~~

(btw, is the pre-push hook really necessary? It prevents me from pushing even to my own fork)

closes #8

### CODE REVIEW

**Comment by bebraw** [comment]
Can you update the change log?

How does pre-push fail for you? The pre-push thinger gained a Windows fix a while ago that might help. I can also change it to other solution.

**Comment by bebraw** [comment]
I see now, pre-push probably failed with lint. `eslint --fix` should fix most of those.

**Comment by SebastianS90** [comment]
I'll work on this a bit (see TODO List in updated post above)
Can you give me a pointer to the `webpack-defaults` that you mentioned [here](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/8#issuecomment-280059291)?

**Comment by bebraw** [comment]
Sure. See https://github.com/webpack-contrib/webpack-defaults . The idea is that the command will sync to defaults maintained in that repo. Still a bit experimental.

**Comment by bebraw** [comment]
You can skip the pre-push hook with `git push --no-verify`.

**Comment by SebastianS90** [comment]
Okay, after looking into `webpack-defaults` I can summarize:
* it pulls in the eslint configuration from [eslint-config-webpack](https://github.com/webpack-contrib/eslint-config-webpack)
* but that project uses a different configuration than webpack/webpack
* the project is still unreleased
* correct me if I'm wrong, but I guess the ultimate goal is to have webpack/webpack using this eslint configuration, too

So what I did instead of trying to get the same eslint configuration:
* make the plugin pass eslint as configured in this repository
* added the changelog entries

What remains as TODO for the future:
* Make sure this repository uses the same eslint configuration as webpack/webpack, preferably a configuration provided in `eslint-config-webpack` that can be simply imported

**Comment by bebraw** [comment]
> correct me if I'm wrong, but I guess the ultimate goal is to have webpack/webpack using this eslint configuration, too

Yeah, I'll poke about that. Thanks for the insights.

I'll try to get some answers and merge the PR. 👍

**Comment by bebraw** [comment]
I have a decision on this. Webpack core and contrib will follow styles of their own. That said, to keep the core and this plugin in sync, we should move this plugin to follow the core `.eslintrc`. After that these operations would be just copying (minimal effort).

How does that sound?

**Comment by SebastianS90** [comment]
Sounds good! Unfortunately, due to time constraints, I cannot do the refactoring.

You could merge this PR and afterwards revert 71c3d3f6ab688518971088554ef9f68982af1f0c. Then you have an almost-copy of the plugin from webpack/webpack, where only the [two relative requires](https://github.com/webpack/webpack/blob/d0f1f6e77009599618b571f9d57bb2a53ba1a583/lib/optimize/UglifyJsPlugin.js#L11:L12) have been adjusted. Afterwards you need to adjust `.eslintrc` and the other javascript files such that the linter does not complain.

**Comment by bebraw** [comment]
Ok, sounds good. Thanks. 👍

**Pull request merged**
